version: "3.7"

services:
  db:
    image: mysql:5.7
    volumes:
      - data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=bdash_server_dev
    ports:
      - "3307:3306"
  db_test:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=bdash_server_dev
    ports:
      - "3308:3306"

volumes:
  data:
