services:
  db:
    image: mysql:8.0
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=bdash_server_dev
    ports:
      - "3307:3306"

volumes:
  mysql-data:
